sudo: required
services:
        - docker
before_install:
        - docker build -t tomaszklawa/complex -f ./client/Dockerfile.dev ./client


script:
        - docker run -e CI=true tomaszklawa/complex/react-test npm test -- --coverage

after_success:
        - docker build -t tomaszklawa/complex-client ./client
        - docker build -t tomaszklawa/complex-nginx ./nginx
        - docker build -t tomaszklawa/complex-sever ./server
        - docker build -t tomaszklawa/complex-worker ./worker

#docker login
#
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push tomaszklawa/complex-client
        - docker push tomaszklawa/complex-nginx
        - docker push tomaszklawa/complex-sever
        - docker push tomaszklawa/complex-worker

