sudo: required
services:
        - docker
before_install:
        - docker build -t tomaszklawa/complex-test -f ./client/Dockerfile.dev ./client


script:
        - docker run -e CI=true tomaszklawa/complex-test npm test -- --coverage

after_success:
        - docker build -t tomaszklawa/complex-client ./client
        - docker build -t tomaszklawa/complex-nginx ./nginx
        - docker build -t tomaszklawa/complex-server ./server
        - docker build -t tomaszklawa/complex-worker ./worker

#docker login
#
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push tomaszklawa/complex-client
        - docker push tomaszklawa/complex-nginx
        - docker push tomaszklawa/complex-server
        - docker push tomaszklawa/complex-worker
        
deploy:
    provider: elasticbeanstalk
    region: 'eu-central-1'
    app: 'complex'
    env: 'Complex-env-1'
    bucket_name: 'elasticbeanstalk-eu-central-1-548309142200'
    bucket_path: 'copmlex'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY        

